### ISSUE TITLE
Modernization megaticket

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#133]
webdiff no longer works for me on macOS Catalina so it's high time to update it!

Things on my laundry list:

- Python
  - [x] Fix packaging errors (#131)
  - [x] Get rid of `README` in favor of `README.md`
  - [x] Format with black
  - [x] Eliminate dependency on Flask (#91)
  - [x] Get rid of `testing.cfg` and all config stuff (just use environment variables)
  - [x] Packaging
    - [x] Move nose and black into the equivalent of `devDependencies`
    - [x] Set up piptools / poetry for dependencies
    - [x] Figure out how to dedupe `install_requires` in `setup.py` and `requirements.txt`
    - [x] De-dupe version number between `app.py` and `setup.py`
  - [ ] #170
  - [x] Eliminate dependency on `requests`
  - [x] Switch from black -> ruff
  - [x] Set up pyproject.toml (https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-your-project-to-pypi)
  - [x] Eliminate Python 2 shims (just use Python 3) 2024: I'm not sure what this refers to.
- JavaScript
  - [x] Replace bower with npm or yarn and unbundle packages except codediff.js (#128)
  - [x] Use a more modern version of React
  - [x] Convert to TypeScript
  - [x] Format with prettier
  - [x] Replace underscore with lodash
  - [x] Get rid of grunt
  - [x] Use jest in place of qunit
  - [x] Keep `package.json` version in sync with `pyproject.toml` or delete it
  - [x] Set up [knip](https://knip.dev/)
  - [x] Get rid of jQuery dependency (transitive dependency of [codediff.js](https://github.com/danvk/codediff.js))
  - [x] Remove deprecated APIs like `e.keyCode`
- General
  - [x] Use `git` to calculate diffs (#129)
  - [x] Create a homebrew package
  - [x] Set up testing on CircleCI
  - [ ] Switch from CircleCI → GitHub Actions
  - [ ] Switch from Dependabot → Renovate
  - [ ] Set up auto-merge
  - [x] Rename `master` → `main`
  - [x] Change Travis badge to CircleCI in README.md

**Comment by zeptonaut** [comment]
As someone who uses this tool I-don't-even-know-how-many times per day, I was extremely bummed to see that it no longer works on Catalina. Definitely would love to see it working again!

**Comment by danvk** [comment]
@zeptonaut Try updating to 0.15.0? It should work! Glad to hear webdiff has some loyal users :)

**Comment by zeptonaut** [comment]
@danvk Working great now - thanks for this great little utility, Dan! Love how lightweight and flexible it is.
