### ISSUE TITLE
1.0.0 release checklist

### ISSUE THREAD

**Issue by danvk** [danvk/webdiff#158]
- [x] Fix test badge in README.md
- [x] Add PyPI badges: #74
- [x] Fix critical security vulnerabilities (`yarn upgrade`)
- [x] Add a HOST option (in addition to PORT): #123 and #156
- [x] Update screenshots in README.md
- [x] Test on all `testdata` examples
- [x] Test the GitHub integration
- [x] Update homebrew repo (https://github.com/danvk/homebrew-webdiff): https://github.com/danvk/homebrew-webdiff/commit/e5a10092c9e809b1edf47dcd6ba1250473f36717
